### ISSUE TITLE
GraphGist Page Title is "<title>Page Source"

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#65] opened 2015-02-17 17:11 UTC

**Comment by cheerfulstoic** [comment] 2015-02-18 14:04
I'm not able to reproduce this... What browser / URL?

**Comment by jexp** [comment] 2015-02-18 22:52
Not literally `<title>` but "This is a gist titlePage Source"

Chrome, OSX

**Comment by cheerfulstoic** [comment] 2015-02-19 12:12
Sorry, I'm still not able to reproduce...  I'm seeing the gist's title as the <title> of the page wherever I go wether it's in the DB or not.  What URL are you using?  Or is it happening all over?

**Comment by jexp** [comment] 2015-02-19 12:36
It's on the browser tab

Von meinem iPhone gesendet

**Comment by cheerfulstoic** [comment] 2015-02-19 12:39
Ah!  I see it now!  Sorry, I misunderstood what you were saying and the pages that I were checking had titles that were longer than the tab.  I'll fix it now!  Thanks

**Comment by jexp** [comment] 2015-02-19 12:43
Sorry my bad for being not clearer 

Von meinem iPhone gesendet

**Comment by cheerfulstoic** [comment] 2015-02-19 13:50
My fault for not reading carefully enough.  Fixed now

**Closed by cheerfulstoic** 2015-02-19 13:50 UTC
Labels: bug
